"""
รายละเอียด 16 MBTI types — nickname, description, strengths, careers ฯลฯ
ใช้ generate response จาก predictor.py
"""

TYPE_INFO = {
    "INTJ": {
        "nickname": "The Architect (สถาปนิก)",
        "description": "คุณเป็นนักคิดเชิงกลยุทธ์ มองภาพรวมได้ดี ตั้งเป้าหมายชัดเจน และมีวิสัยทัศน์ระยะยาว ทำงานคนเดียวได้ดีเพื่อลงลึกในสิ่งที่สนใจ",
        "strengths": ["วางแผนเป็นระบบ", "มองภาพรวม", "มุ่งมั่นสูง", "ใฝ่รู้"],
        "weaknesses": ["อาจดูเย็นชา", "ใจร้อนกับคนไม่ตามทัน", "บางทียืดหยุ่นน้อย"],
        "careers": ["นักวิทยาศาสตร์", "สถาปนิก", "ที่ปรึกษากลยุทธ์", "วิศวกร", "ผู้ก่อตั้งบริษัท"],
        "famous_people": ["Elon Musk (debated)", "Nikola Tesla", "Christopher Nolan"],
        "compatible": ["ENFP", "ENTP"],
    },
    "INTP": {
        "nickname": "The Logician (นักตรรกะ)",
        "description": "คุณช่างสงสัย ชอบวิเคราะห์ลึก มี mental model ของตัวเองและกล้าท้าทาย assumption ต่างๆ",
        "strengths": ["วิเคราะห์ลึก", "สร้างสรรค์", "ยืดหยุ่นทางความคิด", "เป็นกลาง"],
        "weaknesses": ["ตัดสินใจช้า", "ขาดการเข้าสังคม", "หลงลืมรายละเอียดปลีกย่อย"],
        "careers": ["นักวิจัย", "Data Scientist", "Software Engineer", "นักปรัชญา"],
        "famous_people": ["Albert Einstein", "Bill Gates", "Marie Curie"],
        "compatible": ["ENTJ", "ENFJ"],
    },
    "ENTJ": {
        "nickname": "The Commander (ผู้บัญชาการ)",
        "description": "ผู้นำตามธรรมชาติ ตัดสินใจเด็ดขาด กล้าเสี่ยง และขับเคลื่อนทีมสู่เป้าหมาย",
        "strengths": ["ภาวะผู้นำ", "ตัดสินใจเด็ดขาด", "มีวิสัยทัศน์", "มั่นใจสูง"],
        "weaknesses": ["อาจครอบงำคนอื่น", "ใจร้อน", "ไม่ค่อยใส่ใจความรู้สึก"],
        "careers": ["CEO", "ทนายความ", "ผู้บริหาร", "นักลงทุน"],
        "famous_people": ["Steve Jobs", "Margaret Thatcher"],
        "compatible": ["INFP", "INTP"],
    },
    "ENTP": {
        "nickname": "The Debater (นักโต้วาที)",
        "description": "ช่างถกเถียง คิดเร็ว ชอบไอเดียใหม่ และรักการเอาชนะทางความคิดอย่างสร้างสรรค์",
        "strengths": ["สร้างสรรค์", "คิดเร็ว", "adaptable", "สื่อสารดี"],
        "weaknesses": ["ไม่อยู่กับที่", "ชอบเถียง", "จบงานยาก"],
        "careers": ["Entrepreneur", "นักการตลาด", "ทนายความ", "Product Manager"],
        "famous_people": ["Mark Twain", "Thomas Edison"],
        "compatible": ["INFJ", "INTJ"],
    },
    "INFJ": {
        "nickname": "The Advocate (ผู้สนับสนุน)",
        "description": "ลึกซึ้ง มีอุดมการณ์ เห็นอกเห็นใจผู้อื่น และมักรู้สึกว่าตัวเองมีภารกิจ",
        "strengths": ["เข้าใจคน", "มีวิสัยทัศน์เชิงคุณค่า", "ตั้งใจ", "ลึกซึ้ง"],
        "weaknesses": ["รับอารมณ์คนอื่นมากเกินไป", "perfectionist", "เก็บตัว"],
        "careers": ["นักจิตวิทยา", "ครู", "นักเขียน", "ที่ปรึกษา"],
        "famous_people": ["Martin Luther King Jr.", "Plato"],
        "compatible": ["ENTP", "ENFP"],
    },
    "INFP": {
        "nickname": "The Mediator (นักไกล่เกลี่ย)",
        "description": "อ่อนโยน มีอุดมคติ สร้างสรรค์ ให้ความสำคัญกับคุณค่าภายในและความจริงใจ",
        "strengths": ["เข้าใจคนลึก", "สร้างสรรค์", "มีคุณค่าชัด", "เปิดรับ"],
        "weaknesses": ["อ่อนไหวมาก", "idealistic เกินจริง", "หลีกเลี่ยง conflict"],
        "careers": ["นักเขียน", "นักจิตวิทยา", "ศิลปิน", "นักสังคมสงเคราะห์"],
        "famous_people": ["William Shakespeare", "J.R.R. Tolkien"],
        "compatible": ["ENFJ", "ENTJ"],
    },
    "ENFJ": {
        "nickname": "The Protagonist (ผู้ชี้นำ)",
        "description": "มีเสน่ห์ อบอุ่น ดึงศักยภาพของคนรอบข้าง เก่งการสื่อสารและ inspire",
        "strengths": ["ผู้นำที่เห็นใจ", "สื่อสารดี", "inspire คนได้", "จัดระเบียบเก่ง"],
        "weaknesses": ["รับภาระผู้อื่นมากเกินไป", "ไวต่อคำวิจารณ์", "idealist"],
        "careers": ["ครู", "HR", "Coach", "นักการทูต"],
        "famous_people": ["Barack Obama", "Oprah Winfrey"],
        "compatible": ["INFP", "ISFP"],
    },
    "ENFP": {
        "nickname": "The Campaigner (นักรณรงค์)",
        "description": "กระตือรือร้น สร้างสรรค์ สดใส เห็นความเป็นไปได้ใหม่ ๆ และเชื่อมคนได้ดี",
        "strengths": ["พลังงานสูง", "สร้างสรรค์", "เข้ากับคนง่าย", "มองโลกกว้าง"],
        "weaknesses": ["สมาธิสั้น", "ขี้หลง", "รู้สึกมากไป"],
        "careers": ["นักการตลาด", "นักข่าว", "Entrepreneur", "Designer"],
        "famous_people": ["Robin Williams", "Robert Downey Jr."],
        "compatible": ["INTJ", "INFJ"],
    },
    "ISTJ": {
        "nickname": "The Logistician (นักปฏิบัติ)",
        "description": "รับผิดชอบสูง น่าเชื่อถือ ทำตามระเบียบ ชอบความมั่นคงและผลงานที่จับต้องได้",
        "strengths": ["รับผิดชอบ", "ทำตามกฎ", "รายละเอียดดี", "อดทน"],
        "weaknesses": ["ยืดหยุ่นน้อย", "เคร่งเกินไป", "ต้านทานการเปลี่ยนแปลง"],
        "careers": ["บัญชี", "วิศวกร", "ทหาร", "ผู้ตรวจสอบ"],
        "famous_people": ["George Washington", "Warren Buffett"],
        "compatible": ["ESFP", "ESTP"],
    },
    "ISFJ": {
        "nickname": "The Defender (ผู้พิทักษ์)",
        "description": "อบอุ่น อ่อนน้อม ใส่ใจคนรอบข้าง ทำงานเบื้องหลังให้ทุกอย่างเรียบร้อย",
        "strengths": ["ใส่ใจ", "รับผิดชอบ", "เห็นอกเห็นใจ", "มุ่งมั่น"],
        "weaknesses": ["ไม่กล้าปฏิเสธ", "ชอบ routine", "กลัวการเปลี่ยนแปลง"],
        "careers": ["พยาบาล", "ครู", "นักสังคมสงเคราะห์", "เลขา"],
        "famous_people": ["Mother Teresa", "Kate Middleton"],
        "compatible": ["ESTP", "ESFP"],
    },
    "ESTJ": {
        "nickname": "The Executive (ผู้บริหาร)",
        "description": "มีระเบียบ เด็ดขาด เป็นผู้บริหารที่เก่งการจัดการและทำตามมาตรฐาน",
        "strengths": ["จัดการเก่ง", "ตรงไปตรงมา", "อดทน", "น่าเชื่อถือ"],
        "weaknesses": ["ดื้อรั้น", "ตัดสินเร็วเกินไป", "ไม่ยืดหยุ่น"],
        "careers": ["ผู้จัดการ", "ทหาร", "ผู้พิพากษา", "นักบัญชี"],
        "famous_people": ["John D. Rockefeller", "Judge Judy"],
        "compatible": ["ISFP", "ISTP"],
    },
    "ESFJ": {
        "nickname": "The Consul (ผู้ให้คำปรึกษา)",
        "description": "อบอุ่น ชอบช่วยเหลือ เป็นที่รักของเพื่อน ๆ ใส่ใจความสัมพันธ์",
        "strengths": ["เข้ากับคน", "ให้กำลังใจ", "จัดงานเก่ง", "ปฏิบัติได้จริง"],
        "weaknesses": ["ต้องการการยอมรับ", "หลีกเลี่ยง conflict", "อ่อนไหวต่อคำวิจารณ์"],
        "careers": ["HR", "พยาบาล", "ครู", "Event Planner"],
        "famous_people": ["Taylor Swift", "Bill Clinton"],
        "compatible": ["ISFP", "ISTP"],
    },
    "ISTP": {
        "nickname": "The Virtuoso (จอมเทคนิค)",
        "description": "ช่างคิด ช่างทำ ชอบลงมือและเข้าใจกลไกของสิ่งต่าง ๆ ด้วยการทดลอง",
        "strengths": ["practical", "แก้ปัญหาเฉพาะหน้า", "ใจเย็น", "adaptable"],
        "weaknesses": ["เก็บอารมณ์", "ไม่ชอบกฎ", "เบื่อง่าย"],
        "careers": ["ช่าง", "นักบิน", "วิศวกร", "Firefighter"],
        "famous_people": ["Clint Eastwood", "Michael Jordan"],
        "compatible": ["ESFJ", "ESTJ"],
    },
    "ISFP": {
        "nickname": "The Adventurer (นักผจญภัย)",
        "description": "อ่อนโยน สร้างสรรค์ ใช้ชีวิตในปัจจุบัน รักความสวยงามและเสรีภาพ",
        "strengths": ["ศิลปะ", "อ่อนโยน", "เปิดรับ", "adaptable"],
        "weaknesses": ["อ่อนไหว", "แข่งขันไม่ถนัด", "วางแผนระยะยาวยาก"],
        "careers": ["ศิลปิน", "Designer", "นักดนตรี", "Chef"],
        "famous_people": ["Bob Dylan", "Michael Jackson"],
        "compatible": ["ESFJ", "ENFJ"],
    },
    "ESTP": {
        "nickname": "The Entrepreneur (ผู้กล้าเสี่ยง)",
        "description": "พลังล้น ตัดสินใจเร็ว ชอบสถานการณ์จริง รักการเผชิญหน้ากับความท้าทาย",
        "strengths": ["กล้าเสี่ยง", "เข้ากับคนง่าย", "ตัดสินใจเร็ว", "practical"],
        "weaknesses": ["ไม่ชอบวางแผน", "ใจร้อน", "เบื่อง่าย"],
        "careers": ["Sales", "นักกีฬา", "นักลงทุน", "Entrepreneur"],
        "famous_people": ["Ernest Hemingway", "Madonna"],
        "compatible": ["ISFJ", "ISTJ"],
    },
    "ESFP": {
        "nickname": "The Entertainer (ผู้สร้างความบันเทิง)",
        "description": "สดใส ร่าเริง อยู่กับปัจจุบัน รักการใช้ชีวิตและทำให้คนรอบข้างมีความสุข",
        "strengths": ["energetic", "friendly", "practical", "สร้างความสุข"],
        "weaknesses": ["ไม่ชอบวางแผน", "หลีกเลี่ยง conflict", "อ่อนไหว"],
        "careers": ["นักแสดง", "นักร้อง", "ครู", "Event Host"],
        "famous_people": ["Marilyn Monroe", "Elvis Presley"],
        "compatible": ["ISTJ", "ISFJ"],
    },
}


def get_info(mbti: str) -> dict:
    """Return info for given type, fallback to INTJ if unknown."""
    return TYPE_INFO.get(mbti, TYPE_INFO["INTJ"])
